### ISSUE TITLE
Display message to user if user is unable to sign up

### ISSUE THREAD

**Issue by harurang** [cerberus-org/cerberus-app#29]
Error thrown in sign up component should be displayed to the user instead of being logged in the console. 

Should we use a modal?

**Comment by tlmader** [comment]
Consider using a snack bar for this.

**Comment by harurang** [comment]
I kind of like the dialog more, but I guess this will mostly depend on the design of the application. i.e. if the sign up functionality is a modal or page.

**Comment by tlmader** [comment]
If it's just a message, I don't see the point of a modal. Using a modal means users need to click another button just to retry. Snack bars are great at notifying/engaging users without adding extra steps.

**Comment by tlmader** [comment]
I'd use a modal if extra functionality is needed.

**Comment by harurang** [comment]
No longer needed because a user cannot select submit if parameters are not valid.
