### ISSUE TITLE
Improve check-in UI and handle errors

### ISSUE THREAD

**Issue by harurang** [cerberus-org/cerberus-app#35]
- [x] Volunteer cannot check in if they have not signed up

- [x] Highlight 'Sign-Up?' if check-in search returns an empty list

- [x] Redirect user to check in page after sign up

- [x] Add back button on sign up page

**Comment by tlmader** [comment]
Would the back button still be beneficial with our current structure?

**Comment by tlmader** [comment]
Closing this in favor of more specific UI issues.
